[Code][Gameplay] Camera and Enhanced Input System
Team-BNUY/gamelab_project_bunny pull request #15
Opened 2022-02-16 15:23 UTC by DrakeHunterK7

Contains:

- Cinemachine customizable camera
- Unique player controls for both Gamepad and KB/M

Twin Stick shooter controls for gamepad, and mouse-driven player rotation for KB/M

2022-02-16 22:30 UTC, George540 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +using Cinemachine;
Remove unused variables and packages

2022-02-16 22:32 UTC, George540 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +        [Range(0.0f, 90f)] private float _cameraAngle;
Can these be changed from the Cinemachine component? If so, no need to have them here

2022-02-16 22:33 UTC, George540 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +                    Debug.Log(finalRotation);
Remove debug statements. Unnecessary cluttering of console. Only use them for test purposes

2022-02-16 22:33 UTC, George540 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +                if (_playerCamera is { })
Invert if statement. Rider can do that automatically if you select the suggestion button on the left

2022-02-16 22:35 UTC, George540 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +                    if(inputRotationR.magnitude > 0.1f || inputRotationL.magnitude > 0.1f)
Put if statement in brackets...always. Only one liner if statement allowed are the ones Rider suggests, which are usually the invert if statements. Also, you did not ident this right. This is why ALWAYS put if statements on brackets. Read code standards again

2022-02-16 22:36 UTC, George540 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +                    Vector2 inputRotationR = gamepad.rightStick.ReadValue();
Use var type for local variables within methods

2022-02-16 22:36 UTC, George540 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +                Debug.Log(rotation);
No debugs allowed

2022-02-16 22:38 UTC, George540 requested changes
A lot of coding standard changes are required

2022-02-16 22:40 UTC, George540 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +                            Vector3 stickDirection = _playerCamera.transform.position + (new Vector3(inputRotationL.x, 0, inputRotationL.y) * 500f);
Put var for these local variables again. Everything declared within a method are declared with var

2022-02-18 06:04 UTC, DrakeHunterK7 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +                    Debug.Log(finalRotation);
Donezo

2022-02-18 06:04 UTC, DrakeHunterK7 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +        [Range(0.0f, 90f)] private float _cameraAngle;
Everything about the camera can be changed in the Cinemachine component itself, so this is definitely useless here. Good catch!

2022-02-18 06:05 UTC, DrakeHunterK7 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +                if (_playerCamera is { })
Done, downloaded Rider and fixed this.

2022-02-18 06:06 UTC, DrakeHunterK7 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +                    Vector2 inputRotationR = gamepad.rightStick.ReadValue();
Done 2: Return of the Done

2022-02-18 06:06 UTC, DrakeHunterK7 commented
> A lot of coding standard changes are required

Agreed and thank you very much for calling me out on these. Definitely will improve going forward. Thanks!

2022-02-18 06:06 UTC, DrakeHunterK7 commented on Project Bunny/Assets/Scripts/Input/StudentController.cs
> +                            Vector3 stickDirection = _playerCamera.transform.position + (new Vector3(inputRotationL.x, 0, inputRotationL.y) * 500f);
Done

2022-02-18 06:30 UTC, Cappic-01 approved these changes
Coding conventions corrected and Cinemachine looking good!

2022-02-19 06:25 UTC, George540 approved these changes
Very good, yum yum

2022-02-19 07:27 UTC, George540 approved these changes
Cool cool

2022-02-19 21:34 UTC, Cappic-01 approved these changes
Btw if using Summaries, don't forget to also describe any parameter and what the function returns. There are fields generated automatically just for that in the Summary block.

2022-02-19 22:31 UTC, merged