36 [Code][Gameplay] Cannon
Team-BNUY/gamelab_project_bunny pull request #37
Opened 2022-03-02 23:33 UTC by DrakeHunterK7

- Created IInteractable Interface for use by all Interactables
- Created Slingshot/Cannon using the aforementioned interface. 
- Created Cannonball prefab for Slingshot

Instructions:
Press 'E' to begin using the slingshot when standing close to the Slingshot. Press 'E' to forfeit control of it. Left Click to start aiming the Slingshot then let go of Left Click to shoot.

2022-03-03 04:47 UTC, George540 commented on Project Bunny/Assets/Scripts/Player/Cannon.cs
> +        private StudentController _playerScript;
name it _studentController, so it's easy to access it without having to think how it's named

2022-03-03 04:47 UTC, George540 commented on Project Bunny/Assets/Scripts/Player/Cannon.cs
> +        private CinemachineVirtualCamera _cameraSettings;
Same here

2022-03-03 04:50 UTC, George540 commented on Project Bunny/Assets/Scripts/Player/Cannon.cs
> +            _player = GameObject.FindWithTag("Player");
Avoid using Find() Can you make a function that finds the reference from the StudentController? I think on the OnInteract function, you can pass the StudentController.cs component as a parameter

2022-03-03 04:50 UTC, George540 commented on Project Bunny/Assets/Scripts/Player/Cannon.cs
> +            _playerScript = _player.GetComponent<StudentController>();
As the comment mentioned above, same here

2022-03-03 04:50 UTC, George540 commented on Project Bunny/Assets/Scripts/Player/Cannon.cs
> +            _playerCharController = _player.GetComponent<CharacterController>();
Same here

2022-03-03 04:51 UTC, George540 commented on Project Bunny/Assets/Scripts/Player/Cannon.cs
> +            var componentBase = _cameraSettings.GetCinemachineComponent(CinemachineCore.Stage.Body);
Can you make a camera script that accesses these components easily instead of having to do GetCinemachineComponent all the time?

2022-03-03 04:54 UTC, George540 commented on Project Bunny/Assets/Scripts/Player/Cannon.cs
> +        private void ThrowSnowball()
A lot of the code is from the StudentController.cs script. Why not use those instead of copy-pasting them here?

2022-03-03 04:54 UTC, George540 commented on Project Bunny/Assets/Scripts/Player/Cannon.cs
> +        private float MousePosToRotationInput(Vector2 mousePos)
Same for this one. You can reuse them

2022-03-03 04:56 UTC, George540 commented on Project Bunny/Assets/Scripts/Player/StudentController.cs
> +        private IInteractable ReturnNearestInteractable()
Why not use the OnCharacterCollisionHit() function callback instead? You can handle multiple interactables at once, but usually none of them will be close to one another

2022-03-03 04:58 UTC, George540 requested changes
Good work! But there are some redundancies that can be avoided. Will make the transfer to the network easier

2022-03-03 22:07 UTC, DrakeHunterK7 commented on Project Bunny/Assets/Scripts/Player/StudentController.cs
> +        private IInteractable ReturnNearestInteractable()
The idea here is to call the ReturnNearestInteractable() function when the player pressesn the 'E' key, and not when the player collides with the gadget. If that makes sense.

2022-03-03 22:09 UTC, Cappic-01 reviewed
Looks good to me excluding the requested changes by George. Will rereview and approve once a review will be requested again.

2022-03-04 00:01 UTC, DrakeHunterK7 commented
I removed some redundancies but I couldn't simplify the Cannonball throwing and aiming logic code since even though the code is doing the same things as StudentController.cs, the variables affected are different for both the StudentController.cs and Cannon.cs so it's safer to just keep the Cannonball throwing and aiming logic the way it is. 

Also added a Utilities script to add all utilities that can be used by multiple scripts.

2022-03-04 02:26 UTC, George540 approved these changes
Good work!

2022-03-04 02:33 UTC, KristianKurk approved these changes
looks clean, left a little comment but it's just an organizational thing

2022-03-04 02:33 UTC, KristianKurk commented on Project Bunny/Assets/Scripts/Player/Cannon.cs
> +        [SerializeField] [Min(0)] private float _rotationSpeed;
group your serializefield variables if you can

2022-03-04 02:39 UTC, merged