[Code] [Network] Working lobby and player
Team-BNUY/gamelab_project_bunny pull request #38
Opened 2022-03-03 23:51 UTC by KristianKurk

no way to go back to lobby/quit a room/etc, it's a one way street

2022-03-04 00:32 UTC, Cappic-01 approved these changes
Looks clean! Left two minor comments just in case it's not cause of Photon, but otherwise good!

2022-03-04 00:32 UTC, Cappic-01 commented on Project Bunny/Assets/Scripts/Networking/ArenaManager.cs
> +    [SerializeField] private GameObject _playerPrefab;
You could make this as a NetworkStudentController to avoid mistakes, unless it's required by Photon?

2022-03-04 00:32 UTC, Cappic-01 commented on Project Bunny/Assets/Scripts/Networking/LobbyManager.cs
> +        [SerializeField] private TMP_InputField createInput;
A few underscores missing for private members, again unless it's required by Photon?

2022-03-04 01:00 UTC, George540 commented on Project Bunny/Assets/Scripts/Networking/LobbyManager.cs
> +            joinButton = joinInput.GetComponentInChildren<Button>();
Any way you can reference these without GetComponentInChildren()?

2022-03-04 01:01 UTC, George540 commented on Project Bunny/Assets/Scripts/Networking/PlayerTile.cs
> +        if (team == 1)
brackets between if statements, in case we need more functionality

2022-03-04 01:02 UTC, George540 commented on Project Bunny/Assets/Scripts/Networking/PlayerTile.cs
> +        this.text.text = text;
Lol double text.text?

2022-03-04 01:03 UTC, George540 commented on Project Bunny/Assets/Scripts/Networking/RoomManager.cs
> +            if (PhotonTeamsManager.Instance.GetTeamMembersCount(1) <= PhotonTeamsManager.Instance.GetTeamMembersCount(2))
If Rider suggests it, you can turn this into a conjunction statement

2022-03-04 01:05 UTC, George540 requested changes
Lookin good broski, just a lil fine tuning and I'll approve it

2022-03-04 04:24 UTC, George540 approved these changes
Looks good! Just check Julien's and my comments

2022-03-08 21:39 UTC, KristianKurk commented on Project Bunny/Assets/Scripts/Networking/ArenaManager.cs
> +    [SerializeField] private GameObject _playerPrefab;
It's a prefab that needs to be instantiated, so it needs to be a GameObject. Unless if there's some way to require component on a prefab, but I'm not aware of it.

2022-03-08 21:46 UTC, KristianKurk commented on Project Bunny/Assets/Scripts/Networking/RoomManager.cs
> +            if (PhotonTeamsManager.Instance.GetTeamMembersCount(1) <= PhotonTeamsManager.Instance.GetTeamMembersCount(2))
i use visual studio xd

2022-03-08 22:54 UTC, merged